service: metis-clockify-updater
app: metis-clockify-updater
provider:
  name: aws
  runtime: python3.7
  stage: prod
  region: us-east-1
  timeout: 900
  environment:
    DB_HOSTNAME: ${DB_HOSTNAME}
    DB_NAME: ${DB_NAME}
    DB_USERNAME: ${DB_USERNAME}
    DB_PASSWORD: ${DB_PASSWORD}
    DB_PORT: ${DB_PORT}
    ENVIRONMENT: ${ENVIRONMENT}
    CLOCKIFY_API_KEY: ${CLOCKIFY_API_KEY}
    CLOCKIFY_WORKSPACE_ID: ${CLOCKIFY_WORKSPACE_ID}

functions:
  update:
    handler: handler.update
    events:
      - schedule: rate(15 minutes)

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: 'non-linux'
    usePipenv: false
    zip: true

package:
  exclude:
    - migrations/**
    - old_timesheet_migration/**
    - seeds/**
    - services/**
    - node_modules/**
    - setup.cfg
    - README.md
    - Pipfile
    - Pipfile.lock
    - orator_config.py
    - update_member_clt.py
    - .env
    - .python-version
    - .pre-commit-config.yaml
    - .codeclimate.yml